name: Test

on: [push, pull_request]

jobs:
  build-test-windows:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    env:
      LIBRARY_PREFIX: $env:CONDA_PREFIX\Library

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: latest
          environment-file: environment.yml
          init-shell: >-
            powershell

      # - name: Show conda installation info
      #   run: |
      #     conda info
      #     conda list

      - name: Set the FC environment variable to the Fortran conda compiler
        run: |
          echo "FC=$env:CONDA_PREFIX/Library/bin/flang.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      # - name: Set the FC environment variable to the Fortran conda compiler
      #   run: |
      #     echo "FC=C:/Users/runneradmin/miniconda3/envs/fbld/Library/bin/flang.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure Meson project
        run: |
          meson setup build --prefix $env:CONDA_PREFIX
        shell: pwsh

      # - name: Build project
      #   run: |
      #     meson compile -C build

      # - name: Install project
      #   run: |
      #     meson install -C build

      # - name: Build project with pip
      #   run: |
      #     python -m pip install . -v

      # - name: Build wheel
      #   run: |
      #     $env:INCLUDE="C:\Users\runneradmin\miniconda3\envs\fbld\Library\include;$env:INCLUDE"
      #     mkdir build
      #     python -m build -w -n -x -Cbuilddir="build" -Cinstall-args="--tags=runtime,python-runtime,devel" -Csetup-args="-Dcpp_std=c++11" -Csetup-args="-Dfortran_std=none"

      - name: Test import
        working-directory: ${{ github.workspace }}/examples
        run: |
          python -c 'import pymt_ecsimplesnow'
          python -c 'from pymt.models import ECSimpleSnow'

      # The bmi-tester isn't available for bmi-fortran=1.2
      # - name: Test BMI
      #   run: |
      #     make test

      - name: Run examples
        working-directory: ${{ github.workspace }}/examples
        run: |
          python ecsimplesnow_pymt_ex.py
